# Generated by Django 3.1 on 2020-09-03 06:23

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('page01', '0002_auto_20200903_1446'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='page',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(default='피드', max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(default='익명', max_length=50),
        ),
    ]
